### ISSUE TITLE
0.0.13 "release" missing release and tag

### ISSUE THREAD

**Issue by dennisjbell** [cloudfoundry/bosh-docker-cpi-release#20]
https://github.com/cloudfoundry/bosh-docker-cpi-release/commit/3b2e1c07d317cc3967ee658ff96f2fee28e0dcef is marked as the 0.0.13 release, but there is no release for it under the releases url, nor is there a tag for it, unlike all previous releases.  Please add this as soon as possible, as it is currently breaking our build automation.  

Thank you very much!

**Comment by jpalermo** [comment]
Should be a release and tag now
